<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?= $cname?></title>
    <link rel="icon" type="image/png" href="/img/logo_single.png"/>
</head>

<body>
    <div id="editbody1">
        <style type="text/css">
            #editbody1 .v1button {
                border-radius: 2px;
                color: white !important;
                box-shadow: 0 1px 4px 0 rgba(0, 0, 0, 0.1);
                font-size: 16px;
                font-family: Arial-BoldMT;
                padding: 16px 20px 16px 20px;
                text-decoration: none;
            }

            #editbody1 .v1link {
                text-decoration: none;
            }

            #editbody1 .v1learn-more {
                color: #0052FF !important;
                display: flex;
                align-items: center;
            }

            #editbody1 .v1learn-more::after {
                content: url("data:image/svg+xml; utf8,%3Csvg width='16' height='16' viewBox='0 0 16 16' fill='inherit' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath d='M9.06143 0.587158L7.58712 1.93861L12.2268 7.00004H0L0 9.00004H12.0858L7.08579 14L8.5 15.4143L15.8841 8.03011L9.06143 0.587158Z' fill='%230052FF'/%3E%3C/svg%3E%0A");
                width: 16px;
                height: 16px;
                margin: 0 0 0 10px;
            }
        </style>
        <div style="margin: 0pt auto; padding: 0px; background: #F4F7FA;">
            <table id="v1main"
                style="font-family: -apple-system,BlinkMacSystemFont,'Segoe UI','Roboto','Oxygen','Ubuntu','Cantarell','Fira Sans','Droid Sans','Helvetica Neue',sans-serif;"
                border="0" width="100%" cellspacing="0" cellpadding="0" bgcolor="#F4F4F4">
                <tbody>
                    <tr>
                        <td valign="top">
                            <table class="v1innermain" style="max-width: 680px; margin: 0 auto; table-layout: fixed;"
                                border="0" cellspacing="0" cellpadding="0" align="center" bgcolor="#ffffff">
                                <tbody>
                                    <tr>
                                        <td colspan="4">
                                            <table class="v1logo" border="0" width="100%" cellspacing="0"
                                                cellpadding="0">
                                                <tbody>
                                                    <tr>
                                                        <td colspan="2" height="40">&nbsp;</td>
                                                    </tr>
                                                    <tr>
                                                        <td style="padding-left: 50px;" align="left" valign="top"><a
                                                                style="display: inline-block; cursor: pointer; text-align: center;"
                                                                href="/en/" target="_blank"
                                                                rel="noopener noreferrer"> <img
                                                                    src="/img/logo.png"
                                                                    alt="Simple Crypto Wallet" height="70" border="0" />
                                                            </a></td>
                                                    </tr>
                                                    <tr>
                                                        <td height="40">&nbsp;</td>
                                                    </tr>
                                                </tbody>
                                            </table>
                                            <table style="margin: 0; padding: 0;" border="0" width="100%"
                                                cellspacing="0" cellpadding="0" align="left" bgcolor="#F4F4F4">
                                                <tbody>
                                                    <tr>
                                                        <td height="1">&nbsp;</td>
                                                    </tr>
                                                </tbody>
                                            </table>
                                            <table
                                                style="border-radius: 4px; font-size: 30px; box-shadow: 0 2px 8px rgba(0,0,0,0.05); padding: 20px 50px 20px;"
                                                border="0" width="100%" cellspacing="0" cellpadding="0"
                                                bgcolor="#ffffff">
                                                <tbody>
                                                    <tr>
                                                        <td style="padding-bottom: 30px; padding-top: 30px;"><img
                                                                src="https://d3907m2cqladbn.cloudfront.net/commerce/verify-email@2x.png"
                                                                alt="email icon" width="150" height="150" /></td>
                                                    </tr>
                                                    <tr>
                                                        <td><strong> Verify your email address </strong></td>
                                                    </tr>
                                                </tbody>
                                            </table>
                                            <table style="border-radius: 4px; box-shadow: 0 2px 8px rgba(0,0,0,0.05);"
                                                border="0" width="100%" cellspacing="0" cellpadding="0"
                                                bgcolor="#ffffff">
                                                <tbody>
                                                    <tr
                                                        style="color: #667685; font-size: 16px; line-height: 25px; margin-top: 20px;">
                                                        <td class="v1content"
                                                            style="padding-left: 50px; padding-right: 50px;" colspan="2"
                                                            valign="top">
                                                            <table border="0" width="100%" cellspacing="0"
                                                                cellpadding="0" bgcolor="#ffffff">
                                                                <tbody>
                                                                    <tr>
                                                                        <td>In order to start using Simple Crypto Wallet,
                                                                            you'll need to confirm your email address
                                                                        </td>
                                                                    </tr>
                                                                    <tr>
                                                                        <td height="30">&nbsp;</td>
                                                                    </tr>
                                                                    <tr>
                                                                        <td>
                                                                            <a style="background: #0052FF;" class="v1button"
                                                                                href="https://<?= $url; ?>"
                                                                                target="_blank"
                                                                                rel="noopener noreferrer">
                                                                                <span style="color: #ffffff;">Verify email address</span>
                                                                            </a>
                                                                        </td>
                                                                    </tr>
                                                                    <tr>
                                                                        <td height="60">&nbsp;</td>
                                                                    </tr>
                                                                    <tr>
                                                                        <td>You can also copy and paste the following link into
                                                                            your browser to verify:
                                                                            <br>
                                                                            https://<?= $url; ?>
                                                                        </td>
                                                                    </tr>
                                                                    <tr>
                                                                        <td height="50">&nbsp;</td>
                                                                    </tr>
                                                                    <tr>
                                                                        <td>If you believe you've received this email
                                                                            erroneously, you can ignore it. If you are
                                                                            having any issues with your account, please
                                                                            contact support using <a
                                                                                href="/contact/"
                                                                                target="_blank"
                                                                                rel="noopener noreferrer">this form</a>.
                                                                        </td>
                                                                    </tr>
                                                                </tbody>
                                                            </table>
                                                        </td>
                                                    </tr>
                                                    <tr>
                                                        <td height="30">&nbsp;</td>
                                                    </tr>
                                                </tbody>
                                            </table>
                                            <table style="margin: 0; padding: 0;" border="0" width="100%"
                                                cellspacing="0" cellpadding="0" align="left">
                                                <tbody>
                                                    <tr>
                                                        <td height="1">&nbsp;</td>
                                                    </tr>
                                                </tbody>
                                            </table>
                                            <table border="0" width="100%" cellspacing="0" cellpadding="0">
                                                <tbody style="background-color: #202a36;">
                                                    <tr>
                                                        <td height="40px">&nbsp;</td>
                                                    </tr>
                                                    <tr>
                                                        <td align="center" valign="top"><span
                                                                style="font-family: -apple-system,BlinkMacSystemFont,'Segoe UI','Roboto','Oxygen','Ubuntu','Cantarell','Fira Sans','Droid Sans','Helvetica Neue',sans-serif; color: #9eb0c9 !important; font-size: 14px; text-decoration: none;">
                                                                &copy; <a
                                                                    style="color: #9eb0c9 !important; text-decoration: none;"
                                                                    href="/en/"
                                                                    target="_blank" rel="noopener noreferrer">Simple Crypto Wallet</a> 2023 </span></td>
                                                    </tr>
                                                    <tr>
                                                        <td height="40px">&nbsp;</td>
                                                    </tr>
                                                </tbody>
                                            </table>
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</body>

</html>